name: CI/CD Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test
        run: |
          cd client
          npm install
          npm run test

      - name: Build Docker image
        run: docker build -t myapp:latest -f client/Dockerfile ./client

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: docker push myapp:latest

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          render_deploy_hook_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"image": "myapp:latest"}' \
            ${render_deploy_hook_url}
